spring:
  datasource:
    url: ${DB_URL}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml

logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug